_VPATH	+=:$(ROOT)/can/source

PROCOBJ	+= CANConfiguration.o
PROCOBJ	+= CANErrorFunctions.o
PROCOBJ	+= CANEventFunctions.o
PROCOBJ	+= CANFilterFunctions.o
PROCOBJ	+= CANInfoFunctions.o
PROCOBJ	+= CANReceiveFunctions.o
PROCOBJ	+= CANTransmitFunctions.o

